<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Data\VisitData;
use App\Models\Message;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Livewire\WithPagination;
use LivewireUI\Modal\ModalComponent;

class ShowMessageVisits extends ModalComponent
{
    use WithPagination;

    public string $messageId;

    public function mount(string $messageId): void
    {
        $this->messageId = $messageId;
    }

    public static function modalMaxWidth(): string
    {
        return '7xl'; // TODO: Change the autogenerated stub
    }

    public function render(): View|\Illuminate\Foundation\Application|Factory|Application
    {
        return view('livewire.show-message-visits', [
            'visits' => VisitData::collection(Message::findOrFail($this->messageId)->visits()->paginate(2)),
        ]);
    }
}
